providers = ['node']

[phases.setup]
nixPkgs = ['nodejs_20', 'caddy']

[phases.install]
cmds = ['cd web && npm ci']

[phases.build]
cmds = ['cd web && npm run build']

[start]
cmd = 'caddy run --config Caddyfile --adapter caddyfile'
